### PR TITLE
[Bug] Classification dialog is not showing

### LINKED ISSUE #157: [Bug] Classification dialog is not showing
## Problem

The contents of the classification dialog are not visible, only the heading.

Classification dialog only showing the heading

### PR DESCRIPTION
**Pull request by EddieMachete**
Closes #157 

[Figma](https://www.figma.com/file/82mMuohRV0zPWnZbZ5upup/isncsci-app?type=design&node-id=699-51085&mode=design&t=14pHBbRqPfO4aouN-0)

## Problem

The contents of the classification dialog are not visible, only the heading. Layout issues seem to have been introduced when we added the input buttons. Having them as part of the input layout was a bad decision, as they are more of global components that need to be repositioned in the layout. The area with the grids is not properly resizing and showing a scroll bar, but pushing the classification panel out of sight.

Classification dialog only showing the heading

## Solution

1. I moved the **input buttons** out of the **input layout** and make them part of the application layout. There, we can use the `order` property of the `flex` layout to easily reposition the component between medium and large breakpoints without affecting the layout.
2. I set a height for **input layout**. It is arbitrary, it could have been `zero`. It looks like a `height` needs to be specified for the **input layout**. If we leave it as `auto` the `flex-grow: 1` value does not seem to take effect. I do not really know why. This should fix the issue with the grid section not resizing based on the containers height. This brings scrolling back and stopped pushing the **classification** section out of view.

## Testing

- [x] 1. Chromatic visual tests pass

<details>
  <summary>Test case</summary>

  1. Navigate to the [builds section in **Chromatic**](https://www.chromatic.com/builds?appId=64f8d7c6e093108e99084a70&branch=main)
  2. Review any discrepant checks and confirm everything looks as per the designs in [Figma](https://www.figma.com/file/82mMuohRV0zPWnZbZ5upup/isncsci-app?type=design&node-id=699-51085&mode=design&t=14pHBbRqPfO4aouN-0)

</details>

---

- [x] 2. On a large breakpoint the **classification** panel is fully visible at the bottom of the screen

<details>
  <summary>Test case</summary>

  1. Navigate to the developer build https://brave-meadow-05543dc10-158.centralus.4.azurestaticapps.net/
  2. Make the window wider than `764px`
  3. Enter all the required values in the form (complete all cells in grid, VAC and DAP)
  4. Click the calculate button
  5. Confirm the **classification** panel is shown at the bottom of the interface and fully visible
  6. Confirm that by scrolling, you can see all elements of the input layout section

</details>

---

- [x] 3. On a large breakpoint the **input buttons** are at the top of the interface

<details>
  <summary>Test case</summary>

  1. Navigate to the developer build https://brave-meadow-05543dc10-158.centralus.4.azurestaticapps.net/
  2. Make the window larger than `764px`
  3. Confirm that the input buttons are located at the top of the interface

</details>

---

- [x] 4. On a medium breakpoint, or lower the **classification** panel is fully visible as a fullscreen dialog

<details>
  <summary>Test case</summary>

  1. Navigate to the developer build https://brave-meadow-05543dc10-158.centralus.4.azurestaticapps.net/
  2. Make the window narrower than `764px`
  3. Enter all the required values in the form (complete all cells in grid, VAC and DAP)
  4. Click the calculate button
  5. Confirm the **classification** panel fully visible and presented as a fullscreen dialog

</details>

---

- [x] 5. On a medium or smaller breakpoint the **input buttons** are at the bottom of the interface

<details>
  <summary>Test case</summary>

  1. Navigate to the developer build https://brave-meadow-05543dc10-158.centralus.4.azurestaticapps.net/
  2. Make the window narrower than `764px`
  3. Confirm that the input buttons are located at the bottom of the interface

</details>

---

### CODE REVIEW

File: src/app/webApp.ts [hunk 1]
```diff
@@ -31,6 +31,11 @@ export class PraxisIsncsciWebApp extends HTMLElement {
           display: flex;
           flex-direction: column;
         }
+
+        ::slotted(praxis-isncsci-app-layout) {
+          height: 25rem;
```
Comment (EddieMachete) [inline src/app/webApp.ts:36]: This had to be added for the `flex-grow: 1` instruction to take effect and make the **input layout** section resize and present a scrollbar allowing the entire interface to fit inside the container and not push the classification panel out of view.

**Review by praxis-tech — APPROVED** [review]
